# Generated by Django 4.2.5 on 2023-09-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['name'], 'verbose_name': 'Внешние ссылки', 'verbose_name_plural': 'Внешние ссылки'},
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
