# Generated by Django 4.2.5 on 2023-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_links_options_alter_links_name_alter_links_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Язык')),
                ('url', models.URLField(verbose_name='Ссылка на сайт')),
                ('url_support', models.URLField(verbose_name='Ссылка на телеграм-канал техподдержки')),
                ('host', models.GenericIPAddressField(verbose_name='IP хоста')),
                ('port', models.IntegerField(verbose_name='Порт сервера')),
                ('password', models.CharField(max_length=20, verbose_name='Парль сервера')),
                ('encription', models.CharField(max_length=20, verbose_name='Тип шифрования')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ')),
                ('android_client', models.URLField(verbose_name='Ссылка на клиент для Android')),
                ('windows_client', models.URLField(verbose_name='Ссылка на клиент для Windows')),
                ('ios_client', models.URLField(verbose_name='Ссылка на клиент для iOS')),
                ('macos_client', models.URLField(verbose_name='Ссылка на клиент для MacOS')),
                ('chrome_client', models.URLField(verbose_name='Ссылка на клиент для Chrome')),
                ('linux_client', models.URLField(verbose_name='Ссылка на клиент для Linux')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
                'ordering': ['lang'],
            },
        ),
    ]
