# Generated by Django 4.2.5 on 2023-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_blockedsites_alter_settings_url_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsites',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
