# Generated by Django 4.2.5 on 2023-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_blockedsites_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsites',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
