# Generated by Django 4.2.5 on 2023-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_blockedsites_favicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AlterField(
            model_name='blockedsites',
            name='favicon',
            field=models.ImageField(upload_to='upload/', verbose_name='Иконка 16x16'),
        ),
    ]
