# Generated by Django 4.2.5 on 2023-09-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_clients_alter_blockedsites_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='android_client',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='chrome_client',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='encription',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='host',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='ios_client',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='linux_client',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='macos_client',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='password',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='port',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='windows_client',
        ),
    ]
