# Generated by Django 4.2.5 on 2023-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_remove_settings_android_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP хоста'),
        ),
    ]
